"""
Django settings for food_backend project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s@uo5xb3)1_*!)fqo7z!#(i7q91a(+jtcv0nny**qa#pp*j$lc'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
# 跨域问题
ALLOWED_HOSTS = ['*']

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'banner',
    'food',
    'forum',
    'user',
    'django_summernote'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'food_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'food_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'food',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': '12345678',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#     }
# }

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''  # 填入QQ邮箱
EMAIL_HOST_PASSWORD = '' # 填入密码
EMAIL_TIMEOUT = 120  # 增加超时时间到120秒

# Simple-UI
# logo
SIMPLEUI_LOGO = 'http://localhost:9000/static/img/logo.png'
# 首页地址跳转
SIMPLEUI_INDEX = 'http://localhost:5173/'
# 关闭广告
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单。
    'system_keep': False,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。 空列表[] 为全部不显示.
    # 'menu_display': ['任务管理', '权限认证'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': True,

    'menus': [
        {
            'codename': 'banner',
            'name': '广告管理',
            'icon': 'fas fa-ad',
            'models': [
                {
                    'codename': 'banner',
                    'name': '广告信息',
                    'icon': 'fa fa-info',
                    'url': 'banner/ad/',
                }
            ]
        },
        {
            'name': '认证和授权',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '权限组',
                    'icon': 'fas fa-users',
                    'url': 'auth/group/'
                },
                {
                    'name': '用户账户状态',
                    'icon': 'fas fa-user-cog',
                    'url': 'auth/user/'
                },
            ]
        },
        {
            'codename': 'user',
            'name': '用户资料管理',
            'icon': 'fas fa-user',
            'models': [
                {
                    'codename': 'profile',
                    'name': '用户资料信息',
                    'icon': 'fas fa-info',
                    'url': '/admin/user/profile/'
                },

            ]
        },

        {
            'codename': 'food',
            'name': '食品管理',
            'icon': 'fas fa-apple-alt',
            'models': [
                {
                    'codename': 'food',
                    'name': '食品信息',
                    'icon': 'fa fa-info',
                    'url': '/admin/food/food/',
                },
                {
                    'codename': 'nutrition',
                    'name': '食品营养信息',
                    'icon': 'fa fa-cubes',
                    'url': '/admin/food/nutrition/',
                },
                {
                    'codename': 'review',
                    'name': '食品评论信息',
                    'icon': 'fa fa-comment',
                    'url': '/admin/food/review/',
                },
                {
                    'codename': 'price',
                    'name': '食品价格信息',
                    'icon': 'fa fa-jpy',
                    'url': '/admin/food/price/',
                },
                {
                    'codename': 'category',
                    'name': '食品分类信息',
                    'icon': 'fa fa-layer-group',
                    'url': '/admin/food/category/',
                },
                {
                    'codename': 'manufacturer',
                    'name': '食品厂商信息',
                    'icon': 'fa fa-warehouse',
                    'url': '/admin/food/manufacturer/',
                },
            ]
        },
        {
            'codename': 'forum',
            'name': '食品文章管理',
            'icon': 'fa fa-book',
            'models': [
                {
                    'codename': 'article',
                    'name': '文章信息',
                    'icon': 'fa fa-info',
                    'url': '/admin/forum/article/',
                },
                {
                    'codename': 'comment',
                    'name': '文章评论信息',
                    'icon': 'fa fa-comment',
                    'url': '/admin/forum/comment/',
                },
                {
                    'codename': 'category',
                    'name': '文章类别信息',
                    'icon': 'fa fa-layer-group',
                    'url': '/admin/forum/category/',
                },
            ]
        },
    ]
}
