# Generated by Django 4.2.13 on 2024-06-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='地址缩写')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '食品分类',
                'verbose_name_plural': '食品分类',
                'ordering': ('-order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='食品名称')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='地址缩写')),
                ('img', models.ImageField(null=True, upload_to=food.models.food_upload_to, verbose_name='食品图片')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='食品描述')),
                ('shelf_life', models.CharField(blank=True, max_length=20, null=True, verbose_name='保质期')),
                ('storage_conditions', models.TextField(blank=True, null=True, verbose_name='存储条件')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.category', verbose_name='分类')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '食品信息',
                'verbose_name_plural': '食品信息',
                'ordering': ('-order', '-create_time'),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='厂商名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='厂商描述')),
                ('website', models.URLField(blank=True, null=True, verbose_name='官方网站')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='厂商地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱')),
            ],
            options={
                'verbose_name': '食品厂商',
                'verbose_name_plural': '食品厂商',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='食品名称')),
                ('ingredient_name', models.TextField(blank=True, null=True, verbose_name='食品原料')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='卡路里')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='蛋白质')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='脂肪')),
                ('carbohydrates', models.FloatField(blank=True, null=True, verbose_name='碳水化合物')),
                ('fiber', models.FloatField(blank=True, null=True, verbose_name='纤维素')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '食品营养',
                'verbose_name_plural': '食品营养',
                'ordering': ('id', 'update_time'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True, verbose_name='评分')),
                ('body', models.TextField(null=True, verbose_name='评价')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='food.food', verbose_name='食物名称')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='评论作者')),
            ],
            options={
                'verbose_name': '食品评价',
                'verbose_name_plural': '食品评价',
                'ordering': ('-create_time', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='原价')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='折扣价')),
                ('create_time', models.DateField(verbose_name='日期')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='food.food', verbose_name='食物名称')),
            ],
            options={
                'verbose_name': '食品价格',
                'verbose_name_plural': '食品价格',
                'ordering': ('id', 'create_time'),
            },
        ),
        migrations.AddField(
            model_name='food',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.manufacturer', verbose_name='所属厂商'),
        ),
        migrations.AddField(
            model_name='food',
            name='nutrition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.nutrition', verbose_name='食物营养信息'),
        ),
    ]
