# Generated by Django 4.2.13 on 2024-06-01 08:28

import banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='链接')),
                ('img', models.ImageField(null=True, upload_to=banner.models.banner_upload_to, verbose_name='图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'ordering': ('-order', 'id'),
            },
        ),
    ]
