# Generated by Django 4.2.13 on 2024-06-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='头衔')),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='手机')),
                ('wechat', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='微信')),
                ('qq', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='QQ')),
                ('bio', models.TextField(blank=True, default='这个人很懒，什么都没有留下', null=True, verbose_name='简介')),
                ('avatar', models.ImageField(blank=True, default='user/avatar.png', null=True, upload_to=user.models.user_upload_to, verbose_name='头像')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
                'ordering': ('id',),
            },
        ),
    ]
