# Generated by Django 4.2.13 on 2024-06-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='地址缩写')),
                ('img', models.ImageField(null=True, upload_to=forum.models.article_upload_to, verbose_name='图片')),
                ('summary', models.TextField(null=True, verbose_name='摘要')),
                ('body', models.TextField(verbose_name='正文')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览量')),
                ('status', models.CharField(blank=True, choices=[('d', '草稿'), ('r', '审核中'), ('p', '已发表')], default='d', max_length=1, null=True, verbose_name='状态')),
                ('is_top', models.BooleanField(blank=True, default=False, null=True, verbose_name='热门')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '食品文章',
                'verbose_name_plural': '食品文章',
                'ordering': ('-create_time', '-update_time'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名称')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='地址缩写')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('order', models.IntegerField(default=0, verbose_name='级别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'ordering': ('-order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='正文')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('active', models.BooleanField(default=True, verbose_name='有效')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.article', verbose_name='文章')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.comment', verbose_name='父级评论')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
                'ordering': ('create_time',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='forum.category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
        migrations.AddField(
            model_name='article',
            name='voted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='voted_articles', to=settings.AUTH_USER_MODEL, verbose_name='点赞'),
        ),
    ]
